[package]
name = "box2d_sys"
version = "0.1.0"
description = "Bindings for Box2D v3.0"
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/Carroted/box2d_sys"

[build-dependencies]
bindgen = "0.69.4"
cmake = "0.1.50"

[features]
# for compatibility
no_avx2 = []
